# https://www.docker.com/ja-jp/blog/9-tips-for-containerizing-your-node-js-application/

services:
  backend:
    container_name: backend
    restart: always
    # build: backend
    build: .
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    expose:
      - 3000
    tty: true
